---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sealed-gandi
  namespace: external-dns
spec:
  encryptedData:
    GANDI_PAT: AgC0iyz86/EYXbiwAFHMMZ8eeqccbBxUjzOfDp2P77/PP8yWbPPnaRyG/BAedl2ma+JcjRIg+qC/tjtystFJ/7wjdxp7Xru2jtEbAvAlxkepXVq6R3qM7jC1LoWhlIIwskrJNUTLIE4sqQqD0MZtgC8PnxfCEDRxhAqjemQPVKmi/X/OLVpwVsBS3NesuscWrTI4F8Z6fYbnX/QrRRt/IcDXNhS3RqNFqKp5haz6i0MPuI0lalEajnJhN2hk7K6D1Jm//KIM6Ewqg/Bz8dGTSgz7VZPHOC+kx3w7IMeaccs9FBpERTkWHFZUmdT37ceZuTEXM0SjZ/RV0Dw6M8OywRDsJzDSMFEtmfpHaRkl9ZMC5AC/HLWKBZj9JUAX0ow6WjJ95d92AJE1SMK3qdXQImYr0xEwgLA72BB8CPjlrfPgVG+E1l8RjrEdKkEBRpQ8gdUEEa2MuIVKbXKahTLwbyt7ANWESya4AEUZYbz2hvG8J4deMHDhtus6E0b+eiFiLWZdybMdq3Le0pLSTrPzzvyG9Tyxor+0ejTJ969bs9fp7o2oTE60SI9uVYAMyucOUgRAxpq6jlCHeKIALhCycUEag5Xps7fcgfXh51P8YPqBe2nQ9KkpfZ6t4Bf13jURSK47NQ1Xex/ZPumrP89915xXpZyeOpRpn8WvX/SwIUYtsOQhnHNCCq4jpRZZkAGoUMlo5BNQiVVtHFW0O7PSQXPeyEPRPfFlFHMG6vse8XJenJWtlhS/MFlt
  template:
    metadata:
      creationTimestamp: null
      name: sealed-gandi
      namespace: external-dns
