---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sealed-gandi
  namespace: external-dns
spec:
  encryptedData:
    GANDI_PAT: AgBu3PMcVhEJfkOfgCSaqcq58tMIaJUVMWC35Xyj8zEBeNL+eDRWPNN1UfqY17dZK/uRkrOHU3z6hAVj6l2/4nRpKLydFopJqSGCnWZHDRETXXsGR2a7ybierd1IarDw3UFpIdRwoCJ2F7c8YXsNHkLvtIUOfvqqh5ZUJcLIb1zw+t6RRmE43iT7HqjBdHhy2b5+rTZTVwCsGwCqZaXp3kTMOAVUmcYQ7qsFVhFLWo5rsqobuVtI2f8f5ZZADUT21WI0Y9OOr5yjJ9zbMWtiZBW8ElPD/r/WMim8tEfXyTPsE4dmNZ1RgsQ1dt8OJJ7tM239DOB/a/WCPz7aZjAG3xF7ojqQuCpvnRoSdsefr2Ygyl3NOlHxAgEL/YBp5c5Bk363eY5y3Cp7O/ZASR1ENVJzVbN77KAMcEDeG5/+2470jyHKxSmGUFj7bBZSTn5R3IotRpuBmGF2K4EpcuLgAHrH3VAcwe+Krlfi0cXim5sD02IwV7e/1O1RHBSz0IZ+RWP18Fpi0UcOu3LlkKMsmI5qtP4nydmJq5kNNq/hWqMydxTDdPH3M1qc6ijkEn4fdM4GlyBZ4sIJfsAA+01KXaRfMYnbFetj8/xdqZYLT1egzmTOG5hzSbBJR+RZbigaTGhHxJmTisspMaSt0mraGSNAUP+nDiyEik02JPDqzZzHP33HWcEzr9MLnguykzEo4Ks=
  template:
    metadata:
      creationTimestamp: null
      name: sealed-gandi
      namespace: external-dns
