apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-stage-1
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: infra
  source:
    helm:
    path: infra-stage-1
    repoURL: https://github.com/genebean/kubebag.git
    targetRevision: redo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
