apiVersion: v1
appVersion: "1.0"
description: Linkerd Control Plane
name: linkerd-control-plane
version: 0.1.0
dependencies:
- name: linkerd-control-plane
  version: 2024.7.5
  repository: https://helm.linkerd.io/edge
