linkerd-control-plane:
  identityTrustAnchorsPEM: |
    -----BEGIN CERTIFICATE-----
    MIIBjjCCATSgAwIBAgIRALJhLKJv/EDVH6H98zbfIeEwCgYIKoZIzj0EAwIwJTEj
    MCEGA1UEAxMacm9vdC5saW5rZXJkLmNsdXN0ZXIubG9jYWwwHhcNMjQwODA4MTgx
    NTUyWhcNMzQwODA2MTgxNTUyWjAlMSMwIQYDVQQDExpyb290LmxpbmtlcmQuY2x1
    c3Rlci5sb2NhbDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABDxPNZ1F06slqzXu
    fZgGhHEgVRp9ee2E1tf1KJyhDikZGoh16UXgvclOXvWP+ONZcGBeDpc89ZfNActg
    nsjvpxujRTBDMA4GA1UdDwEB/wQEAwIBBjASBgNVHRMBAf8ECDAGAQH/AgEBMB0G
    A1UdDgQWBBSyGugtN3hBBO9nEInRai3AIgWDEzAKBggqhkjOPQQDAgNIADBFAiEA
    vMxCnevumTfcBqUcA4M5pgGDrrfhMaZWUs7grUylo84CIFwuK38DS49yT1ZSPHit
    FltoC5T3ctlQszzX/O5dw6Wu
    -----END CERTIFICATE-----
  identity:
    issuer:
      scheme: 'kubernetes.io/tls'
