apiVersion: v1
appVersion: "1.0"
description: External DNS
name: external-dns
version: 0.1.0
#
dependencies:
- name: external-dns
  version: 1.14.5
  repository: "file://../../forked-charts/external-dns"
# this is not being used. My fork is used instead
# so that I can load a secret via envFrom.
# https://github.com/kubernetes-sigs/external-dns/pull/4671
# apps-of-apps/infra-stage-2/templates/apps/app-external-dns.yaml
# has been updated to account for this.
#
#   repository: https://kubernetes-sigs.github.io/external-dns
