apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd-control-plane
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-90"
spec:
  project: infra
  source:
    chart: linkerd-control-plane
    repoURL: https://helm.linkerd.io/edge
    targetRevision: 2024.7.5
    helm:
      parameters:
        # - name: cniEnabled
        #   value: "true"
        - name: identityTrustAnchorsPEM
          value: |
            -----BEGIN CERTIFICATE-----
            MIIBjjCCATSgAwIBAgIRANOQix65XXwrdU13j0f82rcwCgYIKoZIzj0EAwIwJTEj
            MCEGA1UEAxMacm9vdC5saW5rZXJkLmNsdXN0ZXIubG9jYWwwHhcNMjQwODA1MDIw
            MDA5WhcNMzQwODAzMDIwMDA5WjAlMSMwIQYDVQQDExpyb290LmxpbmtlcmQuY2x1
            c3Rlci5sb2NhbDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABKulSO2ZalPCNEjX
            38FgMaWeO/m4/GCqYDKFk11pdbGG1pxeZvTQ2xwdWPeQfuioH529wVgb7ovQDoRv
            SWKgdB+jRTBDMA4GA1UdDwEB/wQEAwIBBjASBgNVHRMBAf8ECDAGAQH/AgEBMB0G
            A1UdDgQWBBS/v/rMYEEnJJl/fjaYkxnmEYIUwTAKBggqhkjOPQQDAgNIADBFAiEA
            rz66zeL4/sNMTgcGj88AUiLnvoHcO4/IaXu+Y1s70LkCIGvSUabci6yTsPk9htbJ
            mUR5+ko6LM2BKsczUl9MinMI
            -----END CERTIFICATE-----
        - name: identity.issuer.scheme
          value: kubernetes.io/tls
  destination:
    namespace: linkerd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
