apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-90"
spec:
  project: infra
  source:
    repoURL: https://github.com/genebean/kubebag.git
    targetRevision: redo
    path: charts/external-dns
    helm:
  destination:
    namespace: external-dns
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
