traefik:
  ingressClass:
    name: traefik
  ingressRoute:
    dashboard:
      enabled: true
  providers:
    kubernetesCRD:
      ingressClass: traefik
    kubernetesIngress:
      ingressClass: traefik
