---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sealed-gandi
  namespace: external-dns
spec:
  encryptedData:
    GANDI_PAT: AgAzq3zUIEAhNhn08/TQ+Hko1CdENwp5vXnPSUX962s5cA+NnoFHjduOIhysbtanBV5T1ta/pzx1wvcqN1Peq5hdDhZnlVs7EA0MkOd0BRFij2BXk60eSgcrNKNE+e0qtArqDJxI7/b+Y1m9pxhv109Yb0x1/Cn4rn8iBqWBdeW7Wp5MQXLcXgFZ1Eoihjk4SMgAZJBrd+oLOd8cgvgPQw0fbZn8dodJ5wCwQvNp6H3fEVmHjEWnnjiC6q9e2IMEKXX0gln8guwqi6YU6p0aLLCuiAu1jmzhUdkfOZQIGB7+xd6WZTLT7oWWOOp1V3j8Fd9/ykdvSrDu/zs8A6IwM2H+FXR+x2JdCM3um0ov1OdO3mpZzxL8s/bO3SU0q1J2kqFIC9tsfbVFkiXBy3WnvMNsSHgJ/m9cojdC35VqsesNNsphZyS+kKMdR2y/531Cg3eYbNWteeI7RQEuJCix4pOdtJqg7EF8KMMtv7zJE0Fmj+/zK7/5GFN7G+0Jam5fXUV9PlYQnwNEEsrFkYgbR5sEReZrtU9UWm0M711vff6BziBVCxUrZwpA/EQpj6u89pZDjilxpc3aUnGg8mJdp1J2nzt0hv9uapyzCP5e/a8eLEO+CZVTTWHDA8RpvX/UTm98vNlwZAFwYTOVfw8E11XFwoyDAz7vsv8OjXCUATiCseBD+49TLhUwTlIgu6NLzX3BQVCmnGpngsYLUAVcf7EDRdrT8y1OQC85ozosEEhQ8Ut+Sf0doIqS
  template:
    metadata:
      creationTimestamp: null
      name: sealed-gandi
      namespace: external-dns
