---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sealed-gandi
  namespace: external-dns
spec:
  encryptedData:
    GANDI_PAT: foo
  template:
    metadata:
      creationTimestamp: null
      name: sealed-gandi
      namespace: external-dns
    type: kubernetes.io/tls
