apiVersion: v1
appVersion: "1.0"
description: Sealed Secrets
name: sealed-secrets
version: 0.1.0
dependencies:
- name: sealed-secrets
  version: 2.16.1
  repository: https://bitnami-labs.github.io/sealed-secrets
