apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  helm.repositories: |
    - url: https://grafana.github.io/loki/charts
      name: loki
    - url: https://charts.reactiveops.com/stable
      name: reactiveops-stable
    - url: https://charts.jetstack.io
      name: jetstack
    - url: https://openfaas.github.io/faas-netes/
      name: openfaas
  repositories: |
    - url: https://github.com/argoproj/argocd-example-apps.git
    - url: https://github.com/genebean/kubebag.git
  url: https://argocd.192.168.50.240.nip.io
