apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - https://github.com/argoproj/argo-cd/manifests/cluster-install?ref=v1.2.5
resources:
  - argocd-ingress.yaml
patchesStrategicMerge:
  - argocd-cm.yaml
namespace: argocd
